server:
  port: "8080"
  host: "127.0.0.1"

database:
  host: "localhost"
  port: "3306"
  user: "asl_user"
  password: "asl_password_2024"
  name: "asl_market"

jwt:
  secret: "asl-market-jwt-secret-key-production-2024"
  expiry_hours: 168  # 7 days

cors:
  allowed_origins: 
    - "http://localhost:5173"
    - "http://localhost:3000"
    - "https://asllmarket.com"
    - "https://www.asllmarket.com"
    - "http://asllmarket.com"
    - "http://www.asllmarket.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
    - "X-Requested-With"

openai:
  api_key: "your-openai-api-key"
  api_url: "https://api.openai.com/v1/chat/completions"
  model: "gpt-3.5-turbo"
  max_tokens: 1000
  temperature: 0.7

sms:
  api_key: "OWY5ZTAyMjEtMThmNi00NzRiLWFhOTItZTEwMmFhNDQzZTliZTcwM2EzODg5NzUzNWMwOWE3ZDliYWUyYTExMWZlMzY="
  originator: "10002040006050"
  pattern_code: "9i276pvpwvuj40w"