server:
  port: "8080"
  host: "127.0.0.1"  # فقط localhost (nginx proxy میکنه)

database:
  host: "localhost"
  port: "3306"
  user: "asl_user"
  password: "asl_password_2024"
  name: "asl_market"

jwt:
  secret: "your_production_super_secret_jwt_key_change_this_immediately"
  expiry_hours: 168  # 7 days

cors:
  allowed_origins: 
    - "https://asllmarket.com"
    - "https://www.asllmarket.com"
    - "http://asllmarket.com"
    - "http://www.asllmarket.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
    - "X-Requested-With"

openai:
  api_key: "your_openai_api_key"
  api_url: "https://api.openai.com/v1/chat/completions"
  model: "gpt-4"
  max_tokens: 2000
  temperature: 0.7 